server:
  port: 80

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用ip地址
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka