server:
  port: 80

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用ip地址
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false