server:
  port: 9527

spring:
  application:
    name: mloineservicecloud-getway


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: getway-9527.com  #自定义服务信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: mloine-mloineservicecloud
  github: https://github.com/mloine
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
  author.name: mloine
  author.phone: 15618975413
  author.wx: xyk15618975413

zuul:
  routes:
    mydept.serviceId: mloineservicecloud-dept
    mydept.path: /mydept/**
  #ignored-services: mloineservicecloud-dept
  ignored-services: "*"
  prefix: /mloine



